---
all:
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/id_rsa

clickhouse:
  hosts:
    clickhouse_host:
      ansible_host: 158.160.110.172
      internal_ip: 192.168.10.16

vector:
  hosts:
    vector_host:
      ansible_host: 89.169.141.11
      internal_ip: 192.168.10.30

lighthouse:
  hosts:
    lighthouse_host:
      ansible_host: 158.160.125.230
      internal_ip: 192.168.10.14

